### ISSUE TITLE
Feature: Access to current time for animation

### ISSUE THREAD

**Issue by follower** [libfive/libfive#114]
My understanding is that Studio is currently focused on CAD-style output but it seems to have potential for a VJ/generative/live coding animated output too.

Even a basic "one liner" like this produces quite a cool effect:

    (attract (array-xy (box #[-1 -1 -1] #[1 1 1]) 4 4 #[3 3]) #[5 5 -5] 4.5)

![libfive-screenshot-play001-b](https://user-images.githubusercontent.com/189962/35802631-afe92a5e-0ad5-11e8-856c-a4ef2024f3f3.png)

And I can't help thinking it would look even cooler if it was animated e.g. with a rotation and `attract` radius that varied over time... :)

Perhaps a "Studio Live" offshoot? :D

(I have a vague recollection that one of your posts about libfive/Ao mentioned the possibility of time as an input but when I went looking for it I couldn't find it.)

Do you have plans to add functionality like this and/or would you be interested in a patch to do something like this?

**Comment by mkeeter** [comment]
Interesting idea!

I think that's a bit out-of-scope for Studio itself, because it adds complication to core code-paths for a niche feature.

Still, this is the kind of tool-building that I'd like to encourage, building on `libfive` and `libfive-guile`.  If you end up prototyping something, I'd be glad to give feedback and link to it from the `libfive` homepage!  I'd recommend either forking Studio, or – to start on a smaller scale – looking at what I did with [ao-guile-repl](https://github.com/mkeeter/ao-guile-repl).
