### ISSUE TITLE
Dependency required versions too high for Ubuntu

### ISSUE THREAD

**Issue by thehans** [libfive/libfive#130]
The Readme.md says libfive requires guile 2.2, and instructs to apt install `guile-2.2-dev` however, the newest version available, is `guile-2.0-dev`

It looks like guile-2.2 will be available in Ubuntu 18.04 "bionic", when that comes out, but that is not yet released:
https://packages.ubuntu.com/search?keywords=guile-2.2-dev&searchon=names&suite=all&section=all

Is the recommended action to build guile 2.2 from source?  
Is it possible that libfive can work on guile 2.0 at all?

The other issue is the Qt 5.7 requirement.  My distribution has packages for 5.5 only.  Is it possible this can still work?
It looks like qt 5.7 was first made available in Ubuntu "zesty" 17.04.  But unfortunately my package base is still Ubuntu "xenial" 16.04 LTS.
https://packages.ubuntu.com/search?keywords=qtbase5-dev&searchon=names&suite=all&section=all

Note: Ubuntu 16.04 is still the most recent LTS (long term support) release at the time of writing this.

### Versions
- Operating system: Linux Mint 18.3 (based on Ubuntu 16.04 LTS)
- Qt version (if applicable):  qtbase5-dev   Version: 5.5.1+dfsg-16ubuntu7.5

**Comment by mkeeter** [comment]
For the GUI, Guile 2.2 is definitely required, as I'm using the [sandbox](https://lists.gnu.org/archive/html/guile-devel/2017-04/msg00034.html).  I suspect it will be hard to build against Guile 2.0 in general, because 2.2 was the first in their [new stable release series](https://www.gnu.org/software/guile/news/gnu-guile-220-released.html), and I didn't take care to use backwards-compatible APIs.

I'm also skeptical about using Qt 5.5, which is before Qt did their C++11 compatibility push (so things like binding signals + slots to lambda functions may not work).

You'll have to install Guile + Qt using instructions from their respective websites; once you've done that, feel free to re-open this issue if you're having trouble building.
