### ISSUE TITLE
loft of rounded-rectangle gives unexpected results

### ISSUE THREAD

**Issue by pdu4** [libfive/libfive#157]
loft of rounded-rectangle gives unexpected results

If you loft two rounded-rectangles together, it gives an unexpected result at the corners/edges

I can get what I want by chopping the top and bottom of a tapered rounded box but it is a bit more complicated and  I thought I would let you know.
 
below is the code I used
```

(loft  (rounded-rectangle[0 0] [4 4] .5)
       (rounded-rectangle[1 1] [3 3] .5)
       0 4)
```

and trying a different way ....

```
(define b (rounded-rectangle [0 0] [4 4] .1))
(loft b
     (move (scale-xyz b [.5 .5 .5]) 
            [1 1 0])
      0 4)
```

I got  similar results 

It might be related to [Garbage polygons mixed in with the good ones #150](https://github.com/libfive/libfive/issues/150) but I am not sure

### Versions

- Operating system: Debian 9
- `libfive` commit hash: N/A (don't know)
  - Is this the latest commit to `master`?  [yes]
- Qt version (if applicable): qt5

Thanks for the great program

**Comment by mkeeter** [comment]
This is because `rounded-rectangle`'s underlying distance field doesn't smoothly expand and contract as you apply an offset.

I've added `rounded-rectangle-exact`, which has a smoothly varying distance field.  Compare `rounded-rectangle` on the left with `rounded-rectangle-exact` on the right:
<img width="1192" alt="screen shot 2018-03-13 at 8 49 44 am" src="https://user-images.githubusercontent.com/745333/37342608-7ce1c620-269b-11e8-92b9-ace3ca233793.png">

Doing the loft with `rounded-rectangle-exact` works as expected:
<img width="1192" alt="screen shot 2018-03-13 at 8 50 22 am" src="https://user-images.githubusercontent.com/745333/37342648-953e26a0-269b-11e8-8d0a-2984099303ad.png">

--------------------------------------------------------------------------------

>The following characters don't show under the "text" command
>"? = * \ [ ] { } < >"
>and everything comes out in all caps

Yes, that's because I haven't gotten around to making those characters.  That code lives [here](https://github.com/libfive/libfive/blob/master/libfive/bind/text.scm), and I've been porting characters from Antimony's [glyphs](https://github.com/mkeeter/antimony/blob/develop/py/fab/shapes.py#L914-L1505); a PR adding some or all of them would be welcome!

--------------------------------------------------------------------------------

>Also what are the dimensions of the exported stl's? I don't think this is mentioned anywhere.

STLs are unitless files.  It's up to you to decide what `1` means in your script; if you make a sphere of radius 1, it will have radius 1 in the STL file.  Many programs that import STLs assume that 1 unit = 1 mm, but that's not a global standard.

**Comment by pdu4** [comment]
Thanks will try to check it out in the next few days



>>  The following characters don't show under the "text" command
>>   "? = * \ [ ] { } < >"
>>  and everything comes out in all caps

> 
> Yes, that's because I haven't gotten around to making those characters. That code lives here, and I've been porting characters from Antimony's glyphs; a PR adding some or all of them would be welcome!

I am really new to github and have little idea about pull requests. patches and diffs. I can do some scheme but it might take a while for me to understand how things work on github)

**Comment by pdu4** [comment]
The loft seems to be working fine with "rounded-rectangle-exact",

I have done  the letters from antimony, but I am not sure about "a" so I included a simpler version which I left commented out. I am also not sure about the "r" as well. I also included "#" "[" "]" "<" ">" and ° , I hope they are acceptable.
Also there was a problem with the "?"  which was already defined so I corrected that (switching "intersection" for "union")

 "* \ { } % & ^ ~ _" and "@" I will leave for a much later time. 

Sorry I have included the whole edited ["text.scm"](https://gist.github.com/pdu4/ff0a7e691b518c4e4760431b5b8d7527) file in a gist as I have am still not sure about pull requests and the like (I also commented out/removed the "string-uppercase as I felt it was no longer necessary).  I think you should browse through it and see if the indentation and everything else is ok and delete the commented code you don't want before you use it (hopefully I have taken out all the "non standard" words) It compiles and seems to be working ok. I will try make a pull request when I have done "{" and "}" and maybe "@" and I have got used to github. but I feel  the most necessary are done. 

There is also a bug I noticed with "Y" and "k" which sometimes( depending on the position) has a line across the space (above for "Y" and both sides for "k" ) I left a commented out line in the shape description of "k" which ensures this does not happen below, but I left the Y alone as I am not sure if the issue is general or just the way I was rendering them (making them readable by extrusion with a 0.1 thickness which sometimes had some side effects).

I hope it is useful to you.

Thanks

**Comment by d01010101** [comment]
There is no `rounded-rectangle-exact` in the current version. Is it supposed to be so?

**Comment by mkeeter** [comment]
The set of potential shapes is infinite, so they're added on an as-needed basis.

See the [`stdlib` README](https://github.com/libfive/libfive/blob/master/libfive/stdlib/README.md) for details on how that works, if you'd like to add it yourself

**Comment by d01010101** [comment]
This changelog from 2018 https://github.com/libfive/libfive/blob/master/CHANGELOG.md says that "added a few more shapes, like rounded-rectangle-exact". I would just like to look into its code. Maybe it can be found somewhere on github?

**Comment by mkeeter** [comment]
Look at commit e8644a0ad5170ec564d69d177c5e81ac5e01c97b

That commit predates switching over to a standard library written in C, and it looks like that shape wasn't ported over.

**Comment by d01010101** [comment]
Maybe for the better, because a loft of two `rounded-rectangle-exact` produces some shape in-between having sharp corners.
