### ISSUE TITLE
`sequence` equivalent for python?

### ISSUE THREAD

**Issue by omgitsraven** [libfive/libfive#395]
I like using the `sequence` function (macro?) to keep arguments near the function name when making very very nested things... is there any possibility of making some similar syntax in Python?

**Comment by mkeeter** [comment]
Have you discovered all of the member functions of the `Shape` class?  It's got CSG functions and the whole `libfive.transforms` namespace (inserted [here](https://github.com/libfive/libfive/blob/master/libfive/bind/python/libfive/shape.py#L162-L172)), so you can do something like

```python
sphere(1)\
    .scale_z(2)\
    .difference(cylinder(0.4, 10, [0, 0, -5]))
```

(the `\` are needed because otherwise Python thinks it's the end of the expression)

**Comment by omgitsraven** [comment]
oh I absolutely had not!  That's perfect, thank you :)
