### ISSUE TITLE
Libfive-studio segfaults with `move(sphere(1),[])` in python

### ISSUE THREAD

**Issue by traverseda** [libfive/libfive#438]
### Description

While playing around with libfive studio last night I entered this snippet, and studio segfaulted.

```python3
from libfive.stdlib import *
move(sphere(1),[])
```

This probably shouldn't segfault the entire studio application, if possible, as a segfault will kill all unsaved work.

### Versions

- Operating system: Arch Linux kde/plasma
- `libfive` commit hash: ae8ade5
  - Is this the latest commit to `master`?  yes

**Comment by mkeeter** [comment]
Interesting – it looks like `ctypes.Structure` will happily construct a `struct` without any arguments, even if it's supposed to take X/Y/Z coordinates (`tvec3` [here](https://github.com/libfive/libfive/blob/master/libfive/bind/python/libfive/ffi.py#L70-L73)).  This obviously blows up, since the fields are set to `None` by default.

**Comment by mkeeter** [comment]
This should be fixed now – turns out you can override the default `ctypes.Structure` constructor, so I made one that takes the right number of arguments.
