### ISSUE TITLE
[Feature request] Support 32bit systems (x86) and add pre-compiled binaries

### ISSUE THREAD

**Issue by luce80** [libfive/libfive#451]
It would be nice to support also 32bit systems and even nicer would be having up-to-date pre-compiled binaries at least of the shared library for all supported platforms (especially x86). This will let using ancient programming languages by ancient people on ancient platforms (that still rock ;) ).

**Comment by mkeeter** [comment]
If you know what breaks on 32-bit platforms, drop a comment in the thread and I can advise on how to fix it.

That being said, as the core maintainer, I'm not going to guarantee support for 32-bit platforms in any way/shape/form.

`libfive` intentionally supports a *small, modern subset* of platforms (macOS 10.14+, Windows 10+, latest Ubuntu LTS, requiring OpenGL 3.x, etc).  This is because in previous projects, I tried to support _everything_, and got tired of it very quickly – for example, I don't even have a 32-bit machine to test on!
