### ISSUE TITLE
Unioning nothing at the top level causes things to mesh very slow

### ISSUE THREAD

**Issue by lf94** [libfive/libfive#550]
Basically I have this: union(nothing, my_complex_shape), which causes the whole thing to mesh very slowly. Any ideas?

**Comment by mkeeter** [comment]
How are you defining "nothing"?

**Comment by lf94** [comment]
not at my comp. at the moment, but pretty sure it's libfive_tree_const(0)

**Comment by mkeeter** [comment]
That would do it – 0 is ambiguously both inside and outside, and `libfive` will take special effort to figure out which one it is!  Instead, pick a big positive value (e.g. 10000), which is unambiguously outside.

**Comment by lf94** [comment]
Roger, I'll give that a shot!

Tangent question: have you had issues with FFI and libfive's threading (I think it has threading right)?

**Comment by mkeeter** [comment]
Yes, it uses threads for meshing / rendering, but that _should_ be relatively safe – IIRC it spins up a bunch of threads at the beginning of a meshing / rendering operation, then waits for them to join when finishing.  I don't think there are any **persistent** thread pools (but it's been a while since I wrote that code).

**Comment by lf94** [comment]
It must be the FFI I'm using then (koffi.dev). When I force libfive to be slow, or evaluate with values I never consume again, everything works. Otherwise, it segfaults. Thanks for letting me know :)
