### ISSUE TITLE
Interval evaluation bug

### ISSUE THREAD

**Issue by wangsong004** [libfive/libfive#574]
### Description

When I use interval evaluation ,I found a bug about libfive::pow
Here is the code:

SECTION("Interval bug")
{
	auto tree = libfive::pow(libfive::abs(libfive::Tree::X()*4), 1.0/3.0f);
	IntervalEvaluator e(tree);
	auto interval = e.eval({ 1,1,1 }, { 2,2,2 });
        auto low_value = interval.lower();
        auto up_value = interval.upper();
        int kkkk = 0;
}

The low_value I obtained is equal to 1
The up_value I obtained is equal to 1

So I think I got the wrong answer.

### Versions
  - Operating system:[Windows ]

**Comment by mkeeter** [comment]
Looking at the implementation of `pow` in `eval_interval.cpp`, the issue is obvious:
```cpp
    static Interval pow(const Interval& a, const Interval& b)
    {
        auto bPt = int(b.lower());

        auto out = boost::numeric::pow(a.i, bPt);
```

This is because `boost::numeric::interval` only supports `pow(interval, int)`:
https://www.boost.org/doc/libs/1_85_0/libs/numeric/interval/doc/interval.htm

I've added checks to `libfive::pow` and `libfive::nth_root` that throw an exception if an invalid input is provided (302553e6aa6ca3cb13b2a149f57b6182ce2406dd)
